### PR TITLE
fix: frozen string literal issue for ruby 3.4.0

### LINKED ISSUE #136: `warning: literal string will be frozen in the future` in ruby 3.4.0-preview2
Warning by https://bugs.ruby-lang.org/issues/20205

```
# bundle exec rake minitest
Run options: --seed 23847

# Running:

/ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
...../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
./ruby-http-client/lib/ruby_http_client.rb:156: warning: literal string will be frozen in the future
./ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
.../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
.../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
.../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
/ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
/ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
....../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
.../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
.../ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
.F./ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
./ruby-http-client/lib/ruby_http_client.rb:143: warning: literal string will be frozen in the future
```

The choices are these

* Use `''.dup` or `String.new('')` or `+''`.
* Magic comment `frozen_string_literal: false` like [Shopify/httpclient](https://github.com/Shopify/httpclient/commit/19790ac5bef02613b368ad7f3443767c8d481ec4#diff-4151207474d94b3b9899760cf8b7deb3aaf5469bbba81e81c695f20cfca518bcR2).
* Ignore warnings until Ruby v3.4 policy is finalized.
* and other...

### PR DESCRIPTION
**Pull request by chaadow**
# Fixes #

Fixes https://github.com/sendgrid/ruby-http-client/issues/136

To prepare for ruby 3.4.0 and making strings frozen by default, I've stumbled upon these string mutations in my specs while trying to send an email

future of frozen string literals in ruby : https://gist.github.com/fxn/bf4eed2505c76f4fca03ab48c43adc72

similar to https://github.com/fog/fog-aws/pull/709

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/sendgrid/ruby-http-client/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://support.sendgrid.com).

### CODE REVIEW

File: lib/ruby_http_client.rb [hunk 1]
```diff
@@ -184,8 +184,8 @@ def build_args(args)
     #   - The final url string
     #
     def build_url(query_params: nil)
-      url = [add_version(''), *@url_path].join('/')
-      url = build_query_params(url, query_params) if query_params
+      url = [add_version(+''), *@url_path].join('/')
+      url = build_query_params(+url, query_params) if query_params
```
Comment (tmimura39) [inline lib/ruby_http_client.rb]: I don't think this `url` is frozen because it is not “string literal” 🤔
```suggestion
      url = build_query_params(url, query_params) if query_params
```

Comment (chaadow) [reply lib/ruby_http_client.rb]: It is.  The line before does a join('/')

So it creates a string literal

Comment (gs-djaniak) [reply lib/ruby_http_client.rb]: @childish-sambino, @rakatyal, @garethpaul, @tmimura39. Sorry to bother you but could look at this one?

Comment (asilano) [reply lib/ruby_http_client.rb]: I agree with @tmimura39 - `url` is a _string_, but it's not a _string literal_. As proof:

```
irb(main):002> a = ["foo", "bar"]
=> ["foo", "bar"]
irb(main):003> a.map! { it << " world" }
(irb):3:in 'block in <top (required)>': can't modify frozen String: "foo" (FrozenError)
	from (irb):3:in 'Array#map!'
	from (irb):3:in '<main>'
	from <internal:kernel>:168:in 'Kernel#loop'
	from /Users/chrishowlett/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/irb-1.15.1/exe/irb:9:in '<top (required)>'
	from /Users/chrishowlett/.local/share/mise/installs/ruby/3.4.1/bin/irb:25:in 'Kernel#load'
	from /Users/chrishowlett/.local/share/mise/installs/ruby/3.4.1/bin/irb:25:in '<main>'
irb(main):004> a.join("/") << "world"
=> "foo/barworld"
```

Another bump for getting this merged - we depend on this gem and it's blocking our ability to enable frozen literals in 3.4, and will (probably) Just Break from Ruby 4

Comment (chaadow) [reply lib/ruby_http_client.rb]: You're right! Idk why I thought it was back then. There are so many recent methods that create frozen strings 

For example "false.to_s" creates a frozen string

Comment (chaadow) [reply lib/ruby_http_client.rb]: Pushed. Thanks

**Review by manisha1997 — DISMISSED** [review]

**Review by manisha1997 — DISMISSED** [review]

**Comment by chaadow** [comment]
@manisha1997 thank you, could you please merge and cut a release please 🙏🏼

**Review by manisha1997 — APPROVED** [review]

**Comment by chaadow** [comment]
@manisha1997 can you please release on RubyGems please??

**Comment by chaadow** [comment]
here: https://rubygems.org/gems/ruby_http_client

**Comment by manisha1997** [comment]
Hello!
We are trying to do the release, we faced some issue during the release. Will try to release as soon as possible.

**Comment by manisha1997** [comment]
Released version 3.6.0

**Comment by a5-stable** [comment]
@manisha1997
Thank you for the release! I’m glad to see it.
It looks like the release notes might refer to the wrong PR:
https://github.com/sendgrid/ruby-http-client/releases/tag/3.6.0

**Comment by manisha1997** [comment]
Hey!
Apologies for the release notes. 
They were added manually.
